FROM node:22.14.0

WORKDIR /app

COPY front-react/package.json front-react/package-lock.json ./
RUN npm install

COPY front-react/ ./

RUN npm run build

FROM nginx:alpine


# Exponha a porta 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
