FROM node:20

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json ./
RUN npm install

COPY frontend/ ./

RUN npm run build

FROM nginx:alpine


# Exponha a porta 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
