// <auto-generated />
using ApiRestFull.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiRestFull.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20250420070432_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiRestFull.Models.AutorModel", b =>
                {
                    b.Property<int>("IdAutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAutor"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAutor");

                    b.ToTable("Autores");

                    b.HasData(
                        new
                        {
                            IdAutor = 1,
                            Nome = "Machado",
                            Sobrenome = "de Assis"
                        },
                        new
                        {
                            IdAutor = 2,
                            Nome = "Clarice",
                            Sobrenome = "Lispector"
                        },
                        new
                        {
                            IdAutor = 3,
                            Nome = "Jorge",
                            Sobrenome = "Amado"
                        },
                        new
                        {
                            IdAutor = 4,
                            Nome = "Cecília",
                            Sobrenome = "Meireles"
                        },
                        new
                        {
                            IdAutor = 5,
                            Nome = "Carlos",
                            Sobrenome = "Drummond de Andrade"
                        });
                });

            modelBuilder.Entity("ApiRestFull.Models.LivroModel", b =>
                {
                    b.Property<int>("IdLivro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLivro"));

                    b.Property<int>("IdAutor")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLivro");

                    b.HasIndex("IdAutor");

                    b.ToTable("Livros");

                    b.HasData(
                        new
                        {
                            IdLivro = 1,
                            IdAutor = 1,
                            Titulo = "Memórias Póstumas de Brás Cubas"
                        },
                        new
                        {
                            IdLivro = 2,
                            IdAutor = 2,
                            Titulo = "A Hora da Estrela"
                        },
                        new
                        {
                            IdLivro = 3,
                            IdAutor = 3,
                            Titulo = "Capitães da Areia"
                        },
                        new
                        {
                            IdLivro = 4,
                            IdAutor = 4,
                            Titulo = "Passaredo"
                        },
                        new
                        {
                            IdLivro = 5,
                            IdAutor = 5,
                            Titulo = "Alguma Poesia"
                        });
                });

            modelBuilder.Entity("ApiRestFull.Models.LivroModel", b =>
                {
                    b.HasOne("ApiRestFull.Models.AutorModel", "AutorModel")
                        .WithMany("Livros")
                        .HasForeignKey("IdAutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutorModel");
                });

            modelBuilder.Entity("ApiRestFull.Models.AutorModel", b =>
                {
                    b.Navigation("Livros");
                });
#pragma warning restore 612, 618
        }
    }
}
